### ISSUE TITLE
vdr crashes if graphlcd plugin is missing

### ISSUE THREAD

**Issue by pbiering** [pbiering/vdr-plugin-reelbox#8]
combination of reelbox+mcli plugin only result in instant crash on start

```
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/sbin/vdr --vfat --shutdown=/opt/reel/sbin/easyvdr-shutdownaction --record'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055a7b7df9849 in cRingBuffer::Size (this=<optimized out>) at ringbuffer.h:39
39	ringbuffer.h: Datei oder Verzeichnis nicht gefunden.
[Current thread is 1 (Thread 0x7fec75d76640 (LWP 27196))]
(gdb) bt
#0  0x000055a7b7df9849 in cRingBuffer::Size (this=<optimized out>) at ringbuffer.h:39
#1  cRingBufferLinear::Put (Count=<optimized out>, Data=<optimized out>, this=0x7261706d6f632022) at ringbuffer.c:310
#2  cRingBufferLinear::Put (this=this@entry=0x7261706d6f632022, 
```

combination of mcli+reelbox+graphlcd works fine -> really strange...

**Comment by pbiering** [comment]
this is totally strange, even happen if "reelbox" plugin is starting in sequence before "graphlcd" - placed a lot of debug lines into code, have still no real clue about the root cause

**Comment by pbiering** [comment]
found that it's only happen now in case of started with --nofb. Once framebuffer device is active, vdr is not crashing but displaying TV.

**Comment by pbiering** [comment]
Latest debug logs show with framebuffer enabled:

```
vdr[28259]: [28259] reelbox: DEBUG ReelBoxDevice.c/SetAudioChannelDevice: virtual void Reel::ReelBoxDevice::SetAudioChannelDevice(int)
vdr[28259]: [28259] reelbox: DEBUG ReelBoxDevice.c/SetAudioChannelDevice: virtual void Reel::ReelBoxDevice::SetAudioChannelDevice(int)
vdr[28259]: [28259] OSD size changed to 720x576 @ 1.42222
vdr[28259]: [28276] reelbox: DEBUG ReelBoxDevice.c/PlayTsAudio: PlayTsAudio: new Apid: 3625
vdr[28259]: [28276] reelbox: DEBUG ReelBoxDevice.c/PlayTsVideo: PlayTsVideo: new Vpid: 3505
vdr[28259]: [28278] mcli: sections assembler thread started (pid=28259, tid=28278, prio=high)
```
while in case of crash it ends here

```
vdr[28042]: [28042] reelbox: DEBUG ReelBoxDevice.c/RestartAudio: RestartAudio, audioOverHDMI_=1, digitalAudio_=0, audioOverHd=1
vdr[28042]: [28042] reelbox: DEBUG ReelBoxDevice.c/SetAudioChannelDevice: virtual void Reel::ReelBoxDevice::SetAudioChannelDevice(int)
vdr[28042]: [28042] reelbox: DEBUG ReelBoxDevice.c/SetAudioChannelDevice: virtual void Reel::ReelBoxDevice::SetAudioChannelDevice(int)
vdr[28042]: [28042] OSD size changed to 720x576 @ 1,42222
vdr[28042]: [28058] reelbox: DEBUG ReelBoxDevice.c/PlayTsAudio: PlayTsAudio: new Apid: 3625
```

**Comment by pbiering** [comment]
root cause found: ringbuffer was not proper set to NULLfor a new instance of the class, fixed by
https://github.com/pbiering/vdr-plugin-reelbox/commit/62daf4f73b31b147a0a6fafc5d3dd4ef707233bd
